export enum MuscleGroup {
    Traps = 'Traps',
    Front_Delts = 'Front Delts',
    Side_Delts = 'Side Delts',
    Rear_Delts = 'Rear Delts',
    Chest = 'Chest',
    Back = 'Back',
    Biceps = 'Biceps',
    Triceps = 'Triceps',
    Anterior_Forearms = 'Anterior Forearms',
    Posterior_Forearms = 'Posterior Forearms',
    Abs = 'Abs',
    Glutes = 'Glutes',
    Adductors = 'Adductors',
    Abductors = 'Abductors',
    Quads = 'Quads',
    Hamstrings = 'Hamstrings',
    Calves = 'Calves',
}